# Generated by Django 3.2.25 on 2024-03-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Anime'), (2, 'Games'), (3, 'Movie')], default=0),
        ),
    ]
